---
- name:  Install Java
  yum:
    name: java-1.8.0-openjdk
    state: present

- name: Set JAVA_HOME environment variable
  lineinfile:
    path: /etc/environment
    regexp: '^JAVA_HOME'
    line: JAVA_HOME=/usr/lib/jvm/jre-1.8.0

- name: Add host entries
  blockinfile:
    path: /etc/hosts
    block: |
      10.123.10.2 host.am400sp.harmannz.github.io
      10.123.10.3 web.am400sp.harmannz.github.io
      10.123.10.4 app.am400sp.harmannz.github.io

      10.123.10.5 sso.am400sp.harmannz.github.io

- name: Install rng-tools
  package:
    name: rng-tools
    state: present

- name: Enable and start rngd service
  service:
    name: rngd
    daemon_reload: yes
    enabled: yes
    state: started

- name: Copy bash prompt
  copy:
    src: bash-prompt-xterm
    dest: /etc/sysconfig/bash-prompt-xterm
    mode: 0755

- name: Copy bashrc
  copy:
    src: bashrc
    dest: /etc/bashrc
    mode: 0755

- name: Configure prompt.sh
  template:
    src: prompt.sh.j2
    dest: /etc/profile.d/prompt.sh
    mode: 0755

- name: Install vim
  package:
    name: vim
    state: present

- name: Install unzip
  package:
    name: unzip
    state: present
