# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.require_version ">= 2.0.0"


required_plugins = %w(vagrant-vbguest vagrant-cachier vagrant-proxyconf)

plugins_to_install = required_plugins.select { |plugin| not Vagrant.has_plugin? plugin }
if not plugins_to_install.empty?
  puts "Installing plugins: #{plugins_to_install.join(' ')}"
  if system "vagrant plugin install #{plugins_to_install.join(' ')}"
    exec "vagrant #{ARGV.join(' ')}"
  else
    abort "Installation of one or more plugins has failed. Aborting."
  end
end

Vagrant.configure("2") do |config|
  config.vm.box = "centos7-ansible"
  config.vm.box_url = "https://tools.siam.education.govt.nz/sources/centos7.box"
  config.vm.box_check_update = false
  config.vbguest.auto_update = false
  config.vm.box_download_insecure = true

  # proxy configuration (needed for JQ)
  config.proxy.http = "http://jos-repo-server.datacom.co.nz:3128"
  config.proxy.https = "http://jos-repo-server.datacom.co.nz:3128"
  config.proxy.no_proxy = "localhost,127.0.0.1,.harmannz.github.io"

  if Vagrant.has_plugin?("vagrant-cachier")
    config.cache.scope = :box
    config.cache.auto_detect = false
    config.cache.enable :yum
  end

  config.vm.define :am400sp, primary: true do |am400sp|
    # Configure network and add vips
    am400sp.vm.provision "shell", path: "configure-network.sh"
    am400sp.vm.provider "virtualbox" do |vb|
      vb.name = "am400sp-ansible"
      vb.memory = 2048
      vb.cpus = 2
    end

    am400sp.vm.hostname = "host.am400sp.harmannz.github.io"
    am400sp.vm.network :private_network, ip: "10.123.10.2", netmask: "255.0.0.0", auto_config: false

    am400sp.vm.provision "ansible_local", type: "ansible_local" do |ansible|
      ansible.install            = true
      ansible.compatibility_mode = "2.0"
      ansible.install_mode       = "default"
      ansible.playbook           = "site.yml"
      ansible.limit              = "all"
      ansible.inventory_path     = "staging/vagrant"

    end

  end

end
