---
- name: Create openam group
  group:
    name: openam
    state: present

- name: Create openam user
  user:
    group: openam
    name: openam
    state: present

- name: Get details of new OpenAM deployment
  stat:
    path: "{{ artifacts_location }}/AM-6.0.0.2.war"
  register: new_openam_st
  changed_when: no

- name: Check for existing OpenAM deployment
  stat:
    path: /var/lib/tomcat/webapps/sso.war
  register: existing_openam_st
  changed_when: no

- block:
    - name: Stop Tomcat
      service:
        name: tomcat
        state: stopped

    - name: Remove existing OpenAM deployment
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - /var/lib/tomcat/webapps/sso.war
        - /var/lib/tomcat/webapps/sso

    - name: Deploy OpenAM
      copy:
        src: "{{ artifacts_location }}/AM-6.0.0.war"
        dest: /var/lib/tomcat/webapps/sso.war
        remote_src: yes
        owner: tomcat
        group: tomcat

    - name: Create OpenAM directories
      file:
        path: "{{ item }}"
        state: directory
        recurse: yes
        owner: tomcat
        group: tomcat
      with_items:
        - /opt/openam
  when: existing_openam_st.stat.checksum is not defined or existing_openam_st.stat.checksum != new_openam_st.stat.checksum

- name: Tools directories
  file:
    path: /opt/openamTools/{{ item }}
    state: directory
  with_items:
    - amster

- name: Tools extracted
  unarchive:
    src: "{{ artifacts_location }}/{{ item.archive }}"
    dest: /opt/openamTools/{{ item.path }}
    owner: openam
    group: openam
  with_items:
    - { archive: 'Amster-6.0.0.zip', path: 'amster'}

- name: Start tomcat
  service:
    name: tomcat
    state: restarted
    enabled: yes

- name: copy openam amster file
  template:
    src: openam_config.amster.j2
    dest: /opt/openamTools/openam_config.amster
    owner: openam
    group: openam

- name: Setup OpenAM
  command: "/opt/openamTools/amster/amster /opt/openamTools/openam_config.amster"

